# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Cadastrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(381, 605)
        MainWindow.setStyleSheet("background-color: rgb(28, 30, 42)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 170, 311, 41))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    background-color: rgb(15, 16, 22)\n"
"}\n"
"QLineEdit{\n"
"    border-left: 5px solid rgb(250, 187, 17);\n"
"    color: rgb(255, 188, 17);\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    font: 75 8pt \"Kartika\";\n"
"    font-size: 15px\n"
"\n"
"}\n"
"QLineEdit{\n"
"    padding-left: 20px;\n"
"}\n"
"QLineEdit:hover{\n"
"    color: rgb(250,187, 17);\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size: 19px;\n"
"    border-left: 3px solid rgb(15, 16, 22);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 230, 311, 41))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    background-color: rgb(15, 16, 22)\n"
"}\n"
"QLineEdit{\n"
"    border-left: 5px solid rgb(250, 187, 17);\n"
"    color: rgb(255, 188, 17);\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    font: 75 8pt \"Kartika\";\n"
"    font-size: 15px\n"
"\n"
"}\n"
"QLineEdit{\n"
"    padding-left: 20px;\n"
"}\n"
"QLineEdit:hover{\n"
"    color: rgb(250,187, 17);\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size: 19px;\n"
"    border-left: 3px solid rgb(15, 16, 22);\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 290, 311, 41))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    background-color: rgb(15, 16, 22)\n"
"}\n"
"QLineEdit{\n"
"    border-left: 5px solid rgb(250, 187, 17);\n"
"    color: rgb(255, 188, 17);\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    font: 75 8pt \"Kartika\";\n"
"    font-size: 15px\n"
"\n"
"}\n"
"QLineEdit{\n"
"    padding-left: 20px;\n"
"}\n"
"QLineEdit:hover{\n"
"    color: rgb(250,187, 17);\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size: 19px;\n"
"    border-left: 3px solid rgb(15, 16, 22);\n"
"}")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 380, 201, 61))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    font-family:Arial,Helvetica,sans-serif;\n"
"    font-size: 16px;\n"
"    \n"
"    background-color: rgb(250, 187, 17);\n"
"\n"
"    color: rgb(135, 102, 20);\n"
"\n"
"    \n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 381, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "GMAIL"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "SENHA"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "SENHA-CONFIRMAR"))
        self.pushButton.setText(_translate("MainWindow", "Registrar"))
