# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(392, 538)
        Dialog.setStyleSheet("background-color: rgb(20, 24, 29)\n"
"")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(40, 170, 291, 51))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    background-color: rgb(15, 16, 22)\n"
"}\n"
"QLineEdit{\n"
"    border-left: 5px solid rgb(250, 187, 17);\n"
"    color: rgb(255, 188, 17);\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    font: 75 8pt \"Kartika\";\n"
"    font-size: 15px\n"
"\n"
"}\n"
"QLineEdit{\n"
"    padding-left: 20px;\n"
"}\n"
"QLineEdit:hover{\n"
"    color: rgb(250,187, 17);\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size: 19px;\n"
"    border-left: 3px solid rgb(15, 16, 22);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 240, 291, 51))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border: none;\n"
"    background-color: rgb(15, 16, 22)\n"
"}\n"
"QLineEdit{\n"
"    border-left: 5px solid rgb(250, 187, 17);\n"
"    color: rgb(255, 188, 17);\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    \n"
"    font: 75 8pt \"Kartika\";\n"
"    font-size: 15px\n"
"\n"
"}\n"
"QLineEdit{\n"
"    padding-left: 20px;\n"
"}\n"
"QLineEdit:hover{\n"
"    color: rgb(250,187, 17);\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size: 19px;\n"
"    border-left: 3px solid rgb(15, 16, 22);\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(40, 310, 291, 51))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    background-color: rgb(250, 178, 0);\n"
"    color: rgb(138, 88, 0);\n"
"    font-family: Arial,Helvetica,sans-serif;\n"
"    font-size: 15px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 390, 131, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 40, 171, 101))
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    font: 8pt \"Dotum\";\n"
"    font-size: 55px;\n"
"}\n"
"QLabel{\n"
"    color: rgb(241, 187, 41);\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 120, 211, 31))
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(138, 105, 23);\n"
"    font-size: 10px;\n"
"    \n"
"    Font-Family:Arial,Helveticac,sans-serif;\n"
"}")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "USUARIO"))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Password"))
        self.pushButton.setText(_translate("Dialog", "Login"))
        self.pushButton_2.setText(_translate("Dialog", "CADASTRAR"))
        self.label.setText(_translate("Dialog", "LOGIN"))
        self.label_2.setText(_translate("Dialog", "FORGOTTEN USERNAME OR PASSWORD?"))
